---
name: module3_task0
on:  # yamllint disable-line rule:truthy
    push:
    schedule:
        - cron: "* 1 * * *"
jobs:
    help:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Make Help
              run: |
                make help
                working-directory: module3_task0
